production:
  clean_empty_pre_alertas:
    class: CleanEmptyPreAlertasJob
    schedule: every day at 3am
  actualizar_tasa_cambio:
    class: ActualizarTasaCambioJob
    schedule: every day at 6am
  marcar_cotizaciones_expiradas:
    class: MarcarCotizacionesExpiradasJob
    schedule: every day at 1am
  marcar_cuotas_vencidas:
    class: MarcarCuotasVencidasJob
    schedule: every day at 1:30am
